### ISSUE TITLE
Doesn't install with node 0.8.0

### ISSUE THREAD

**Issue by maciek-codes** [RandomEtc/ejs-locals#3]
Hi!

I tried to ru my project on node 0.8.0 however I seem to have a problem with ejs-locals:

``` npm
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message No compatible version found: ejs-locals@'>=0.1.3- <0.2.0-'
npm ERR! message No valid targets found.
npm ERR! message Perhaps not compatible with your version of node?
```

**Comment by RandomEtc** [comment]
The engine in package.json is too strict. It should be a matter of changing the ~ to >=?

If you run the tests and everything works under 0.8 I'll happily publish an update.

**Comment by maciek-codes** [comment]
I won't be surprised if I did something wrong, but I run installed the dependencies and run the tests, this is the output:

```
> ejs-locals@0.1.3 test D:\dev\node_modules\ejs-locals
> mocha -r should


D:\dev\node_modules\ejs-locals\test\support\http.js:36
methods.forEach(function(method){
        ^
TypeError: Cannot call method 'forEach' of undefined
    at Object.<anonymous> (D:\dev\node_modules\ejs-locals\test\support\http.
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (D:\dev\node_modules\ejs-locals\test\test.partials
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at D:\dev\node_modules\ejs-locals\node_modules\mocha\bin\_mocha:300:27
    at Array.forEach (native)
    at load (D:\dev\node_modules\ejs-locals\node_modules\mocha\bin\_mocha:29
    at Object.<anonymous> (D:\dev\node_modules\ejs-locals\node_modules\mocha
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:487:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by RandomEtc** [comment]
Thanks for checking this out. I'll try to update my own node install and try this later today or tonight. Hassle me if you don't hear from me by tomorrow.

**Comment by RandomEtc** [comment]
Looks like methods are now in their own module https://github.com/visionmedia/express/commit/170dcc2907e3ae6f114ca775f06352389c651e94

I pushed a new version which works for me in 0.8.0 and 0.6.18 - at least, the tests pass. The 0.8.0 tests seem slower so I'm not sure if there are other hidden problems.

Let me know how it works out - `npm install ejs-locals` should find version 0.1.4. Good luck!

**Comment by maciek-codes** [comment]
Sweet. Works well (with 0.8.2 at the moment). Thank you!

**Comment by RandomEtc** [comment]
Great. Seems fine here too!
